name: Changes Summary

description: "Generate commit message summary using AI from staged diff"

inputs:
  prompt_file:
    description: |
      Prompt file for AI inference
    required: false
    default: ./.github/prompts/commit-message.prompt.yml
  model:
    description: |
      AI model ID
      `gh models list` to see available model IDs. ref: https://github.com/github/gh-models
    required: false
    default: openai/gpt-4o
  max_tokens:
    description: |
      Max tokens for AI output
    required: false
    default: '4000'
  default_title:
    description: |
      Default commit title if empty
    required: false
    default: 'chore: sync schemas'
  default_body:
    description: |
      Default commit body if empty
    required: false
    default: 'Schemas updated.'

outputs:
  title:
    description: 'Commit title'
    value: ${{ steps.parse.outputs.title }}
  body:
    description: 'Commit body'
    value: ${{ steps.parse.outputs.body }}
  has_staged_changes:
    description: 'Whether staged changes exist'
    value: ${{ steps.diff.outputs.has_staged_changes }}

runs:
  using: "composite"
  steps:
    - name: Generate staged diff files
      id: diff
      run: |
        if git diff --staged --quiet; then
          echo "has_staged_changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "has_staged_changes=true" >> $GITHUB_OUTPUT
        git diff --staged --name-status > staged_name_status.txt || true
        git --no-pager diff --staged | head -n 1000 > staged_unified_diff.txt || true

        ls -l
        cat staged_name_status.txt
        cat staged_unified_diff.txt

        awk '{printf "%s ", $0}' staged_name_status.txt > staged_name_status_oneline.txt || true
        sed -E 's/ $//' staged_name_status_oneline.txt > staged_name_status.txt || true && rm -f staged_name_status_oneline.txt || true
        awk '{printf "%s ", $0}' staged_unified_diff.txt > staged_unified_diff_oneline.txt || true
        sed -E 's/ $//' staged_unified_diff_oneline.txt > staged_unified_diff.txt || true && rm -f staged_unified_diff_oneline.txt || true

        ls -l
        cat staged_name_status.txt
        cat staged_unified_diff.txt
      shell: bash
    - name: Generate commit message
      id: generate
      if: steps.diff.outputs.has_staged_changes == 'true'
      uses: actions/ai-inference@v2.0.1
      with:
        prompt-file: ${{ inputs.prompt_file }}
        file_input: |
          name_status: staged_name_status.txt
          unified_diff: staged_unified_diff.txt
        model: ${{ inputs.model }}
        max-tokens: ${{ inputs.max_tokens }}
    - name: Parse generated message
      id: parse
      if: steps.diff.outputs.has_staged_changes == 'true' && steps.generate.outputs.response != ''
      uses: actions/github-script@v8.0.0
      with:
        script: |
          const fs = require('fs');

          const respFileEnv = process.env.MODEL_RESP_FILE;
          let respFile;
          if (respFileEnv && fs.existsSync(respFileEnv)) {
            respFile = respFileEnv;
          } else {
            respFile = '/tmp/generated_commit_message.json';
            fs.writeFileSync(respFile, process.env.MODEL_RESP || '', 'utf8');
          }

          let title = '';
          let body = '';
          try {
            const content = fs.readFileSync(respFile, 'utf8');
            const j = JSON.parse(content);
            title = j.title || '';
            body = j.body || '';
          } catch (e) {
            console.warn(e && e.message ? e.message : String(e));
          }

          if (!title) title = process.env.DEFAULT_TITLE || '';
          if (!body) body = process.env.DEFAULT_BODY || '';

          core.setOutput('title', title);
          core.setOutput('body', body);
      env:
        MODEL_RESP: ${{ steps.generate.outputs.response }}
        MODEL_RESP_FILE: ${{ steps.generate.outputs.response-file }}
        DEFAULT_TITLE: ${{ inputs.default_title }}
        DEFAULT_BODY: ${{ inputs.default_body }}
